Friends/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Friends.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Mobile No. cannot be blank"), MinLength(10,ErrorMessage ="Mobile No. cannot be less than 10 digits"), MaxLength(20)]
        public string MobileNo { get; set; }
        [Required(ErrorMessage = "Password cannot be blank"), MinLength(8,ErrorMessage ="Password cannot be less than 8 characters"), MaxLength(20)]
        public string Password { get; set; }
        public int UserMasterID { get; set; }
        public string EmailID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

Friends/Controllers/LoginController.cs
using Dapper;
using Friends.BusinessLogic;
using Friends.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Friends.Controllers
{
    public class LoginController : Controller
    {
        private IFriends IFriendsfact;
        public LoginController(IFriends _friends)
        {
            IFriendsfact = _friends;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(Login login)
        {
            if (ModelState.IsValid)
            {
                var result = IFriendsfact.CheckLoginDetails(login);
                if (result == null)
                {
                    ViewBag.Message = "Mobile No. or Password is incorrect !!";
                    return View();
                }
                HttpContext.Session.SetString("UserMasterId", Convert.ToString(result.UserMasterID));
            }

            return RedirectToAction("DisplayFriends", "DisplayFriends");
        }
    }
}

Friends/Controllers/UserRegistrationController.cs
using Dapper;
using Friends.BusinessLogic;
using Friends.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Friends.Controllers
{
    public class UserRegistrationController : Controller
    {
        private IFriends IFriendsfact;
        public UserRegistrationController(IFriends _friends)
        {
            IFriendsfact = _friends;
        }
        [HttpGet]
        public IActionResult UserRegistration()
        {
            User user = new User();
            return View(user);
        }


        [HttpPost]
        public IActionResult UserRegistration(User user)
        {
            if (ModelState.IsValid)
            {
                var result = IFriendsfact.SaveUserDetails(user);
                if (result.ErrorCode)
                {
                    TempData["Message"] = result.Message;
                    return View(user);
                }
            }

            return RedirectToAction("Login", "Login");
        }
    }
}

Friends/Views/Login/Login.cshtml
@using Friends.Models
@model Login
@{
    ViewBag.Title = "Login";
    Layout = null;
}

<html>
<head>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm("Login", "Login", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    <label>Mobile No</label>
                    @Html.TextBoxFor(m => m.MobileNo, new { id = "MobileNo" })
                    @Html.ValidationMessageFor(m => m.MobileNo)
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label>Password</label>
                    @Html.TextBoxFor(m => m.Password, new { id = "Password", type = "password" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
            </div>

            <div class="row">
                <h4 class="alert-danger">@ViewBag.Message</h4>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary" value="Login">Login</button>
                    @Html.ActionLink("Signup", "UserRegistration", "UserRegistration", null, new { @class = "btn btn-primary" })

                </div>
            </div>
        }
    </div>

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

</body>



</html>